// ui/src/routes/search/LemmaCard.tsx
import { clsx } from 'clsx';
import { ReactNode, useRef } from 'react';

import {
  AccentDirection,
  Audio,
  Furigana,
  LemmaNoteInfo,
  Word,
} from '../../api/__generated__/graphql';
import PlayIcon from '../../components/Icons/PlayIcon';
import { LemmaBag } from '../../lib/lemma-bag';
import { ToastFunction } from '../../lib/styled-toast';

export type LemmaCardProps = {
  lemmaBag: LemmaBag;
  toast: ToastFunction;
  previewLemma: (lemma: LemmaNoteInfo) => Promise<void>;
};

export default function LemmaCard({ lemmaBag, toast, previewLemma }: LemmaCardProps) {
  return (
    <div className="my-4 rounded-md bg-gray px-10 py-2 shadow-md">
      <div className="flex flex-col divide-y divide-blue">
        <LemmaCardItem render={true}>
          <LemmaTitle word={lemmaBag.slug} toast={toast} />
        </LemmaCardItem>
        <LemmaCardItem render={lemmaBag.slug.hiragana !== '' || lemmaBag.audio.length > 0}>
          <div className="flex flex-row items-start justify-between">
            <Hiragana word={lemmaBag.slug} />
            {lemmaBag.audio.length > 0 && <AudioControls audios={lemmaBag.audio} />}
          </div>
        </LemmaCardItem>
        <LemmaCardItem render={lemmaBag.lemmas.length > 0} className="py-3">
          <Senses projectedLemmas={lemmaBag.lemmas} previewLemma={previewLemma} />
        </LemmaCardItem>
        <LemmaCardItem render={lemmaBag.forms.length > 0}>
          <LemmaForms forms={lemmaBag.forms} />
        </LemmaCardItem>
        <LemmaCardItem render={lemmaBag.tags.length > 0}>
          <Tags tags={lemmaBag.tags} />
        </LemmaCardItem>
      </div>
    </div>
  );
}

function LemmaCardItem({
  render,
  className = 'py-7',
  children,
}: {
  render: boolean;
  className?: string;
  children: ReactNode;
}) {
  if (!render) {
    return null;
  }
  return <div className={className}>{children}</div>;
}

function LemmaTitle(props: { word: Word; toast: ToastFunction }) {
  const { word, toast } = props;
  const copyKanji = () => {
    navigator.clipboard.writeText(word.word);
    toast('Copied ' + word.word);
  };
  return (
    <div>
      <button
        onClick={(e) => {
          e.stopPropagation();
          copyKanji();
        }}
        className="transition-colors duration-300 hover:text-blue active:text-dark-blue"
      >
        <h1 className="text-6xl">
          <RenderWord word={word} />
        </h1>
      </button>
    </div>
  );
}

function Hiragana({ word }: { word: Word }) {
  return (
    <div className="text-2xl leading-10">
      {word.pitchShapes.length == 0
        ? word.furigana.map((e) => e.hiragana).join('')
        : word.pitchShapes.map((pitch, index) => {
            return (
              <span
                key={index}
                className={clsx(
                  'border-blue',
                  pitch.directions.includes(AccentDirection.Up) && 'border-t',
                  pitch.directions.includes(AccentDirection.Down) && 'border-b',
                  pitch.directions.includes(AccentDirection.Right) && 'border-r',
                  pitch.directions.includes(AccentDirection.Left) && 'border-l',
                )}
              >
                {pitch.hiragana}
              </span>
            );
          })}
    </div>
  );
}

function Senses({
  projectedLemmas,
  previewLemma,
}: {
  projectedLemmas: LemmaNoteInfo[];
  previewLemma: (lemma: LemmaNoteInfo) => Promise<void>;
}) {
  return (
    <ol className="-mx-4 text-lg">
      {projectedLemmas.map((projectedLemma, index) => {
        const lemma = projectedLemma.lemma;
        return (
          <li
            className="mb-3 flex flex-row justify-between rounded-xl p-4 last:mb-0 hover:bg-[#fdfdfd]"
            key={index}
          >
            <div>
              <p className="text-blue">{lemma.partsOfSpeech.join(', ')}</p>
              <p className="text-2xl">
                {index + 1}. {lemma.definitions.join('; ')}
              </p>
              <p className="text-dark-gray">{lemma.senseTags.join(', ')}</p>
            </div>
            <div
              className={clsx(
                'flex w-max shrink-0 flex-col place-content-center gap-1 pl-16',
                projectedLemma.noteID ? 'text-blue/60' : 'text-blue',
              )}
            >
              <button
                className="transition-color underline underline-offset-4 transition-colors duration-300 hover:text-green active:text-dark-green"
                onClick={() => previewLemma(projectedLemma)}
              >
                Add to Anki
              </button>
              <div className="self-center text-xs">
                {projectedLemma.noteID && '(already exists)'}
              </div>
            </div>
          </li>
        );
      })}
    </ol>
  );
}

function LemmaForms({ forms }: { forms: Word[] }) {
  return (
    <>
      <p className="text-lg text-blue">Other Forms</p>
      <div className="flex flex-col text-2xl">
        {forms.map((form, index) => {
          return (
            <p key={index}>
              {form.word}
              {form.hiragana ? '「' + form.hiragana + '」' : ''}
            </p>
          );
        })}
      </div>
    </>
  );
}

function Tags({ tags }: { tags: string[] }) {
  return (
    <>
      <p className="text-lg text-blue">Tags</p>
      <div className="flex flex-row justify-items-center gap-7 text-lg">
        {tags.map((tag, index) => (
          <p key={index} className="text-center">
            {tag}
          </p>
        ))}
      </div>
    </>
  );
}

function RenderFurigana(props: { furigana: Furigana }) {
  const { furigana } = props;
  if (furigana.kanji) {
    return (
      <>
        {furigana.kanji}
        <rp>[</rp>
        <rt className="text-lg text-dark-gray">{furigana.hiragana}</rt>
        <rp>]</rp>
      </>
    );
  } else {
    return (
      <>
        {furigana.hiragana}
        <rp>[</rp>
        <rt />
        <rp>]</rp>
      </>
    );
  }
}

function RenderWord(props: { word: Word }) {
  const { word } = props;
  if (word.furigana.length == 0) {
    return <>{word.word}</>;
  } else {
    return (
      <ruby>
        {word.furigana.map((furigana, index) => (
          // use index as key, because word.furigana will never be mutated
          <RenderFurigana key={index} furigana={furigana} />
        ))}
      </ruby>
    );
  }
}

function AudioControls({ audios }: { audios: Audio[] }) {
  const audio = useRef<HTMLAudioElement>(null);
  const handleMouseUp = () => {
    if (!audio.current) {
      return;
    }
    audio.current.play();
  };
  return (
    <div className="flex flex-row gap-2">
      <button
        onClick={(e) => {
          e.stopPropagation();
          handleMouseUp();
        }}
      >
        <PlayIcon className="transition-color h-10 w-10 fill-blue transition-colors duration-300 hover:fill-green active:fill-dark-green" />
      </button>
      <p className="my-auto text-lg leading-5 text-dark-gray">
        Listen to
        <br />
        pronunciation
      </p>
      {/* eslint-disable-next-line jsx-a11y/media-has-caption
       */}
      <audio ref={audio}>
        {audios.map((audio, index) => {
          return <source key={index} src={audio.source} type={audio.mediaType} />;
        })}
      </audio>
    </div>
  );
}

// ui/src/components/LemmaCard.svelte
<script lang="ts">
	import { getNotificationsContext } from 'svelte-notifications';
	import { Lemma, PitchType } from '../api/generated';
	import PlayIcon from './PlayIcon.svelte';

	export let lemma: Lemma;

	const { addNotification } = getNotificationsContext();
	const copy_kanji = () => {
		navigator.clipboard.writeText(lemma.slug.word);
		addNotification({
			text: 'Copied ' + lemma.slug.word,
			position: 'bottom-right',
			removeAfter: 2000
		});
	};

	let audio: HTMLAudioElement;
	const play_mouse_up = () => {
		if (!audio) {
			return;
		}
		audio.play();
	};
</script>

<div
	class="flex flex-col sm:flex-row justify-between shadow-md rounded-md bg-gray my-4 px-8 pt-10 pb-7"
>
	<div class="grow divide-y divide-blue flex-1">
		<div>
			<button
				on:mouseup={copy_kanji}
				class="hover:text-blue active:text-dark-blue transition-colors duration-300"
			>
				<h1 class="text-5xl pb-4">
					{#if lemma.slug.furigana.length == 0}
						{lemma.slug.word}
					{:else}
						<ruby>
							{#each lemma.slug.furigana as furigana}
								{#if furigana.kanji}
									{furigana.kanji}<rp>[</rp><rt class="text-dark-gray text-xl"
										>{furigana.hiragana}</rt
									><rp>]</rp>
								{:else}
									{furigana.hiragana}<rp>[</rp><rt /><rp>]</rp>
								{/if}
							{/each}
						</ruby>
					{/if}
				</h1>
			</button>
		</div>
		{#if lemma.slug.hiragana != ''}
			<div class="text-xl py-4">
				{#if lemma.slug.pitch.length == 0}
					{#each lemma.slug.furigana as furigana}
						{furigana.hiragana}
					{/each}
				{:else}
					{#each lemma.slug.pitch as pitch}
						<span
							class:border-t={pitch.pitch.includes(PitchType.Up)}
							class:border-b={pitch.pitch.includes(PitchType.Down)}
							class:border-r={pitch.pitch.includes(PitchType.Right)}
							class:border-l={pitch.pitch.includes(PitchType.Left)}
							class="border-blue">{pitch.hiragana}</span
						>
					{/each}
				{/if}
			</div>
		{/if}
		{#if lemma.senses.length != 0}
			<div class="text-xl py-4">
				{#each lemma.senses as sense, i}
					<div class="mb-4 last:mb-0">
						<p class="text-base text-blue">{sense.partOfSpeech.join(', ')}</p>
						<p>{i + 1}. {sense.definition.join('; ')}</p>
						<p class="text-base text-dark-gray">{sense.tags.join(', ')}</p>
					</div>
				{/each}
			</div>
		{/if}
		{#if lemma.forms.length != 0}
			<div class="text-xl pt-4">
				<p class="text-base text-blue">Other Forms</p>
				<div class="flex flex-col">
					{#each lemma.forms as form}
						<p>
							{form.word}
							{#if form.hiragana}「{form.hiragana}」{/if}
						</p>
					{/each}
				</div>
			</div>
		{/if}
	</div>
	<div class="shrink sm:basis-8 md:basis-14" />
	<div
		class="flex-none flex flex-col-reverse sm:flex-col justify-items-stretch basis-20 sm:basis-40"
	>
		<button
			class="px-2 py-4 text-xl rounded-md bg-blue hover:bg-green active:bg-dark-green transition-colors duration-300 text-white"
			>Add to Anki</button
		>
		<div class="flex flex-col-reverse sm:flex-col sm:divide-y divide-blue">
			{#if lemma.tags.length != 0}
				<div class="flex flex-col justify-items-center gap-4 py-4 text-lg text-blue">
					{#each lemma.tags as tag}
						<p class="text-center">{tag}</p>
					{/each}
				</div>
			{/if}
			{#if lemma.audio.length != 0}
				<div class="flex flex-row pt-4">
					<button class="m-2" on:mouseup={play_mouse_up}>
						<PlayIcon />
					</button>
					<p class="m-1 text-dark-gray my-auto text-sm leading-5">Listen to pronunciation</p>
					<audio bind:this={audio}>
						{#each lemma.audio as audio}
							<source src={audio.source} type={audio.type} />
						{/each}
					</audio>
				</div>
			{/if}
		</div>
	</div>
</div>
